version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:10.1.0

    steps:
      - checkout
      - restore_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: System information
          command: |
            echo "node $(node -v)"
            echo "npm $(npm -v)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Bootstrap packages
          command: npm run bootstrap
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules
